version: "3"

services:
  wordpress:
    build: .
    ports:
      - 8080:80
    env_file: wp.env
    volumes:
      - .:/var/www/html/wp-content/plugins/colormeshop-wp-plugin
      - vendor_data:/var/www/html/wp-content/plugins/colormeshop-wp-plugin/vendor
    depends_on:
      - composer
      - mysql
    links:
      - mysql

  composer:
    image: composer
    volumes:
      - .:/app
      - vendor_data:/app/vendor
    command: install

  mysql:
    image: mariadb
    env_file: wp.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  vendor_data:
