version: '2'

services:
  wordpress:
    build: .
    ports:
      - 8080:80
    env_file: wp.env
    volumes:
      - .:/var/www/html/wp-content/plugins/colormeshop-wp-plugin

  mysql:
    image: mariadb
    env_file: wp.env
