name: php

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - run: composer install

      - run: ./vendor/bin/phpcs --standard=./ruleset.xml
