name: release

on:
  push:
    tags:
      - "*"

jobs:
  push_to_wordpress_org:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: composer

      - run: composer install --no-dev

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: colormeshop
